{
 "title": "Test Impostor",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "System Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory (Private Bytes)",
     "type": "graph",
     "description": "Memory usage.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "scalar(memory_bytes/1024/1024)", "legendFormat": "Process Private Megabytes" }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "description": "Shows the total number threads and thread pool threads.",
     "gridPos": { "h": 7, "w": 8, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "scalar(total_threads)", "legendFormat": "Total Application Threads" },
      { "expr": "scalar(pool_threads)", "legendFormat": "Thread Pool Threads" }
     ]
    },
    {
     "title": "CPU",
     "type": "gauge",
     "description": "Shows remaining CPU resources",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "scalar(cpu_percent)", "legendFormat": "Usage" }
     ]
    }
   ]
  },
  {
   "title": "Player Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Player Locators",
     "type": "graph",
     "description": "Shows the state of the players.",
     "gridPos": { "h": 7, "w": 19, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "scalar(players_ingame)", "legendFormat": "Players in-game" },
      { "expr": "scalar(players_waiting)", "legendFormat": "Players waiting in lobby" }
     ]
    },
    {
     "title": "Total Players",
     "type": "stat",
     "description": "Total players connected to the server",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "players" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "scalar(players_ingame + players_waiting)",
       "legendFormat": "players"
      }
     ]
    },
    {
     "title": "Chat Messages / second",
     "type": "graph",
     "gridPos": { "h": 6, "w": 19, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "scalar(chat_rate)" }
     ]
    },
    {
     "title": "Chat Message avg. Length",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "scalar(chat_avg_len)",
       "legendFormat": "Average chat length (characters)"
      }
     ]
    },
    {
     "title": "Chat data rate",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "scalar(chat_kbytespersecond)", "legendFormat": "Chat KB/s" }
     ]
    }
   ]
  },
  {
   "title": "Game Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Game Over Reasons",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "scalar(over_human_disconnect)", "legendFormat": "Crewmates disconnected" },
      { "expr": "scalar(over_human_tasks)", "legendFormat": "Completed Tasks" },
      { "expr": "scalar(over_human_vote)", "legendFormat": "Crewmates Voted" },
      {
       "expr": "scalar(over_impostor_disconnect)",
       "legendFormat": "Impostors Disconnected"
      },
      { "expr": "scalar(over_impostor_kill)", "legendFormat": "Impostors Killed Crewmates" },
      { "expr": "scalar(over_impostor_sabotage)", "legendFormat": "Sabotage" },
      { "expr": "scalar(over_impostor_vote)", "legendFormat": "Impostors Voted" }
     ]
    },
    {
     "title": "Lobbies",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "scalar(mirahq_lobbies)", "legendFormat": "MiraHQ Lobbies" },
      { "expr": "scalar(skeld_lobbies)", "legendFormat": "The Skeld Lobbies" },
      { "expr": "scalar(polus_lobbies)", "legendFormat": "Polus Lobbies" },
      { "expr": "scalar(ship_lobbies)", "legendFormat": "Airship Lobbies" },
      {
       "expr": "scalar(mirahq_lobbies+skeld_lobbies+polus_lobbies+ship_lobbies)",
       "legendFormat": "Total Lobbies"
      }
     ]
    }
   ]
  }
 ]
}